### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Connection'

### ISSUE THREAD

**Issue by fones** [dcrosta/professor#13]
I have run `python setup.py install` without errors, and then `python server.py` got me this:
```
$ python server.py
Traceback (most recent call last):
  File "server.py", line 27, in <module>
    from professor import app as application
  File "/Users/fones/Documents/Git/professor/professor/__init__.py", line 44, in <module>
    conn = pymongo.Connection(**app.config.get('MONGODB_CONFIG', {}))
AttributeError: 'module' object has no attribute 'Connection'
```

I am from Node.js env, so dont know much about Python.
My stack: MacOS 10.11.6, Python 2.7.13, MongoDB v3.2.4

**Comment by fones** [comment]
Find a way to fix that. Pull Request above.

**Comment by val922** [comment]
#Examples

https://pypi.python.org/pypi/pymongo/2.8

**Comment by greed2411** [comment]
thanks to @val922.

Im coming here after reading the `Introduction to Tornado, O'reilly book 2012 edition`.

Use `MongoClient` instead of `Connection`

```python3
>>> import pymongo
>>> conn = pymongo.MongoClient('localhost', 27017) #instead of Connection
>>> pymongo.version
'3.6.0'
```
The pymongo api has changed after version `2.8`
