### ISSUE TITLE
error on connecting to mongo 2.2.0 with auth on

### ISSUE THREAD

**Issue by j8mathis** [dcrosta/professor#9]
For whatever reason i am having an issue connecting to one of my mongo instances. I have other instances that are 2.2.1 that connect fine. Not sure where the issue is but thought I would mention it. Below is the server.py output right after I tried to login to the mongo instance.  User Name password are all verified and working. It is an admin user, which works on the other instances. 

Thanks,

Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.8.3-py2.7.egg/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1701, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/app.py", line 1293, in handle_exception
    return handler(e)
  File "/opt/professor/professor/views.py", line 230, in not_found
    return render_template(str(error.code) + '.html')
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/templating.py", line 124, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 758, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 719, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 693, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/dist-packages/Jinja2-2.6-py2.7.egg/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.9-py2.7.egg/flask/templating.py", line 61, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 10057.html

**Comment by j8mathis** [comment]
Man love this tool, I don't think its working correctly with auth on. Cannot connect to any databases with auth on. I just confirmed this with a test locally on my box. Would love a solution don't think I know enough to solve it.
